#!/bin/bash
mydir="$(dirname ${BASH_SOURCE})"
if [ "$1" = "debug" ] ; then
   shift;
   LD_LIBRARY_PATH="${mydir}/src/.libs:${HOME}/opt/zmq/lib" gdb --args "${mydir}/src/.libs/dax_selftest" $@
elif [ "$1" = "memcheck" ] ; then
   shift;
    /bin/bash ./libtool --mode=execute valgrind --tool=memcheck \
	      --leak-check=full --show-reachable=yes --error-exitcode=1 \
	      --suppressions=./src/.valgrind.supp \
	      \
	      ./src/dax_selftest $@

else
   LD_LIBRARY_PATH="${mydir}/src/.libs:${HOME}/opt/zmq/lib" "${mydir}/src/.libs/dax_selftest" $@
fi       
