/*  =========================================================================
    daxproto - generated layer of public API

    LGPL3, boilerplate to come.

################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
    =========================================================================
*/

#ifndef DAXPROTO_LIBRARY_H_INCLUDED
#define DAXPROTO_LIBRARY_H_INCLUDED

//  Set up environment for the application

//  External dependencies
#include <czmq.h>

//  DAXPROTO version macros for compile-time API detection
#define DAXPROTO_VERSION_MAJOR 0
#define DAXPROTO_VERSION_MINOR 0
#define DAXPROTO_VERSION_PATCH 0

#define DAXPROTO_MAKE_VERSION(major, minor, patch) \
    ((major) * 10000 + (minor) * 100 + (patch))
#define DAXPROTO_VERSION \
    DAXPROTO_MAKE_VERSION(DAXPROTO_VERSION_MAJOR, DAXPROTO_VERSION_MINOR, DAXPROTO_VERSION_PATCH)

#if defined (__WINDOWS__)
#   if defined DAXPROTO_STATIC
#       define DAXPROTO_EXPORT
#   elif defined DAXPROTO_INTERNAL_BUILD
#       if defined DLL_EXPORT
#           define DAXPROTO_EXPORT __declspec(dllexport)
#       else
#           define DAXPROTO_EXPORT
#       endif
#   elif defined DAXPROTO_EXPORTS
#       define DAXPROTO_EXPORT __declspec(dllexport)
#   else
#       define DAXPROTO_EXPORT __declspec(dllimport)
#   endif
#   define DAXPROTO_PRIVATE
#elif defined (__CYGWIN__)
#   define DAXPROTO_EXPORT
#   define DAXPROTO_PRIVATE
#else
#   if (defined __GNUC__ && __GNUC__ >= 4) || defined __INTEL_COMPILER
#       define DAXPROTO_PRIVATE __attribute__ ((visibility ("hidden")))
#       define DAXPROTO_EXPORT __attribute__ ((visibility ("default")))
#   else
#       define DAXPROTO_PRIVATE
#       define DAXPROTO_EXPORT
#   endif
#endif

//  Project has no stable classes, so we build the draft API
#undef  DAXPROTO_BUILD_DRAFT_API
#define DAXPROTO_BUILD_DRAFT_API

//  Opaque class structures to allow forward references
//  These classes are stable or legacy and built in all releases
//  Draft classes are by default not built in stable releases
#ifdef DAXPROTO_BUILD_DRAFT_API
typedef struct _dax_timeline_t dax_timeline_t;
#define DAX_TIMELINE_T_DEFINED
typedef struct _dax_timeline_codec_t dax_timeline_codec_t;
#define DAX_TIMELINE_CODEC_T_DEFINED
typedef struct _dax_timeline_server_t dax_timeline_server_t;
#define DAX_TIMELINE_SERVER_T_DEFINED
typedef struct _dax_timeline_client_t dax_timeline_client_t;
#define DAX_TIMELINE_CLIENT_T_DEFINED
#endif // DAXPROTO_BUILD_DRAFT_API


//  Public classes, each with its own header file
#ifdef DAXPROTO_BUILD_DRAFT_API
#include "dax_timeline.h"
#include "dax_timeline_codec.h"
#include "dax_timeline_server.h"
#include "dax_timeline_client.h"
#endif // DAXPROTO_BUILD_DRAFT_API

#ifdef DAXPROTO_BUILD_DRAFT_API

#ifdef __cplusplus
extern "C" {
#endif

//  Self test for private classes
DAXPROTO_EXPORT void
    daxproto_private_selftest (bool verbose, const char *subtest);

#ifdef __cplusplus
}
#endif
#endif // DAXPROTO_BUILD_DRAFT_API

#endif
/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
*/
